[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "https://www.lovelettertales.com/*"
  to = "https://lovelettertales.com/:splat"
  status = 301
  force = true
